# This is an example on how to use the action on a workflow

name: Check vulnerabilities in the PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Check vulnerabilities
      uses: pedrolacerda/scan-commit-for-vulnerable-dependencies@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
